env:
    browser: true
    es2021: true
extends:
    - 'plugin:react/recommended'
    - 'plugin:json/recommended'
    - prettier
settings:
    react:
        version: latest
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - prettier
    - react
    - jsx
    - json
    - import
rules:
    no-console: 'off'
    no-unused-vars: warn
    no-use-before-define: warn
    eqeqeq: warn
    func-names: 'off'
    object-shorthand: 'off'
    no-shadow: 'off'
    spaced-comment:
        - 2
        - always
    consistent-return: 'off'
    no-underscore-dangle: 'off'
    no-param-reassign: error
    no-nested-ternary: 'off'
    arrow-body-style: 'off'
    prefer-arrow-callback: 'off'
    dot-notation: 'off'
    no-tabs: 'off'
    react/prop-types: 'off'
